#!/usr/bin/env bash
##This will say Best School 10 times but it will say hi at the 9th occurance##
num=1
while [ $num -le 10 ]
do
	echo "Best School"
if [ $num -eq 9 ]
then	
	echo "Hi"
fi
##increase by 1 per iteration##
((num++))
done
