#!/usr/bin/env bash
##setting up script that will show Best School 10 times and bad luck at 4, good luck at 8 and Best School for the rest##
num=1
while [ $num -le 10 ]
do
echo "Best School"
if [ $num -eq 4 ]
then echo "bad luck"
fi
if [ $num -eq 8 ]
then echo "good luck"
fi
##increase by 1##
((num++))
done 
