#!/usr/bin/env bash
##setting up script that will show Best School 10 times and bad luck at 4, good luck at 8 and Best School for the rest##
num=1
while [ $num -lt 10 ]
do
if (( $num == 4 ))
	then echo "bad luck"
##checking for the 8th spot##
elif (( $num == 8 ))
then
       	echo "good luck"
else
	echo "Best School"	
fi
##increase by 1##
((num++))
done 
