#!/usr/bin/env bash
##script to show a clock with hour and minutes in between##
HOUR=0
MINUTE=1
while [ $HOUR -le 12 ]
do
	echo "Hour: $HOUR"
while [ $MINUTE -le 59 ]
	do
echo "$MINUTE"

((MINUTE++))
done
##Resets the minute after the hour displays##
MINUTE=1
((HOUR++))
done
