#!/usr/bin/env bash
##Script to give information about a file. in this case school##
if test -f school
then
printf "school file exists"
else 
	echo "school file does not exist"
fi
if test -s school
then
	printf "school file is empty"
else
	echo "school file is not empty"
fi
if test -f school 
then
	printf "school is a regular file"
fi
