#!/usr/bin/env bash
##Script to give information about a file. this is for file- school##
if test -e school
then
echo "school file exists"

if test -e -a -s school 
then
	echo "school file is empty"
else
	echo "school file is not empty"
fi

if test -e -a -f school 
then
	echo "school is a regular file"
fi

else
        echo "school file does not exist"
fi
