#!/usr/bin/env bash
##Script to give information about a file. this is for file- school##
if test -f school
then
echo "school file exists"

if test -z school
then
	echo "school file is empty"
else
	echo "school file is not empty"
fi
if test -d school 
then
	echo "school is a regular file"
	fi
else
        echo "school file does not exist"
fi
